// src/database/members.js
// Array of Objects — FaceApp Community Members

export const membersDB = [
  {
    id: 1,
    name: "Ahmad Raza",
    username: "@ahmad.raza",
    email: "ahmad.raza@faceapp.com",
    age: 22,
    role: "UI Designer",
    city: "Lahore",
    country: "Pakistan",
    verified: true,
    posts: 128,
    followers: 4200,
    following: 310,
    bio: "Passionate designer who loves crafting beautiful digital experiences.",
    joinedDate: "2024-01-15",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad",
    tags: ["Design", "Figma", "Tailwind"],
    rating: 4.8,
  },
  {
    id: 2,
    name: "Sara Ahmed",
    username: "@sara.ahmed",
    email: "sara.ahmed@faceapp.com",
    age: 24,
    role: "Full Stack Dev",
    city: "Karachi",
    country: "Pakistan",
    verified: true,
    posts: 95,
    followers: 3100,
    following: 220,
    bio: "Building scalable web apps with React and Node.js.",
    joinedDate: "2024-02-20",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
    tags: ["React", "Node", "MongoDB"],
    rating: 4.6,
  },
  {
    id: 3,
    name: "Usman Ali",
    username: "@usman.ali",
    email: "usman.ali@faceapp.com",
    age: 20,
    role: "Student",
    city: "Islamabad",
    country: "Pakistan",
    verified: false,
    posts: 40,
    followers: 800,
    following: 500,
    bio: "CS student exploring web development and AI.",
    joinedDate: "2024-03-10",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Usman",
    tags: ["Python", "AI", "Web"],
    rating: 3.9,
  },
  {
    id: 4,
    name: "Fatima Malik",
    username: "@fatima.malik",
    email: "fatima.malik@faceapp.com",
    age: 26,
    role: "UI Designer",
    city: "Lahore",
    country: "Pakistan",
    verified: true,
    posts: 210,
    followers: 7500,
    following: 180,
    bio: "Award-winning designer. Coffee addict. Creating pixel-perfect interfaces.",
    joinedDate: "2023-11-05",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima",
    tags: ["Design", "Branding", "Motion"],
    rating: 4.9,
  },
  {
    id: 5,
    name: "Zara Khan",
    username: "@zara.khan",
    email: "zara.khan@faceapp.com",
    age: 21,
    role: "Content Creator",
    city: "Peshawar",
    country: "Pakistan",
    verified: false,
    posts: 67,
    followers: 1500,
    following: 420,
    bio: "Sharing stories that inspire. Content is king.",
    joinedDate: "2024-04-01",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zara",
    tags: ["Content", "Writing", "Social"],
    rating: 4.1,
  },
  {
    id: 6,
    name: "Bilal Hassan",
    username: "@bilal.hassan",
    email: "bilal.hassan@faceapp.com",
    age: 25,
    role: "Full Stack Dev",
    city: "Karachi",
    country: "Pakistan",
    verified: true,
    posts: 183,
    followers: 5200,
    following: 290,
    bio: "Open source enthusiast. Building tools that matter.",
    joinedDate: "2023-12-18",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bilal",
    tags: ["JavaScript", "Docker", "AWS"],
    rating: 4.7,
  },
  {
    id: 7,
    name: "Ayesha Siddiqui",
    username: "@ayesha.sid",
    email: "ayesha.sid@faceapp.com",
    age: 23,
    role: "Marketing",
    city: "Multan",
    country: "Pakistan",
    verified: true,
    posts: 142,
    followers: 2800,
    following: 350,
    bio: "Digital marketing expert. Growing brands one campaign at a time.",
    joinedDate: "2024-01-28",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ayesha",
    tags: ["Marketing", "SEO", "Analytics"],
    rating: 4.4,
  },
  {
    id: 8,
    name: "Hassan Iqbal",
    username: "@hassan.iq",
    email: "hassan.iq@faceapp.com",
    age: 27,
    role: "DevOps Engineer",
    city: "Lahore",
    country: "Pakistan",
    verified: true,
    posts: 76,
    followers: 3900,
    following: 160,
    bio: "CI/CD pipelines, cloud infra, and clean code advocate.",
    joinedDate: "2023-10-22",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hassan",
    tags: ["DevOps", "Cloud", "Linux"],
    rating: 4.5,
  },
];
